# Generated by Django 3.0.8 on 2020-07-15 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('basemodel_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='common.BaseModel')),
                ('instance_name', models.CharField(max_length=255, verbose_name='Instance name')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('basemodel_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='common.BaseModel')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('street_name', models.CharField(max_length=50, verbose_name='Street name')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Postal code')),
            ],
            bases=('common.basemodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('basemodel_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='common.BaseModel')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Degree', verbose_name='Degree')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('workplace', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Place', verbose_name='Workplace')),
            ],
            bases=('common.basemodel',),
        ),
    ]
