# Generated by Django 3.0.8 on 2020-07-16 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200716_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='account',
        ),
    ]
