# Generated by Django 3.0.8 on 2020-07-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200716_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='instance_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instance name'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='place',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='place',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='place',
            name='street_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Street name'),
        ),
    ]
