# Generated by Django 3.0.8 on 2020-07-23 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CervicClassification',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.BaseModel')),
                ('image', models.ImageField(upload_to='images/')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('DONE', 'Done')], default='WAITING', max_length=10)),
                ('result', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('UNCLASSIFIED', 'Unclassified'), ('UNKNOWN', 'Unknown')], default='UNCLASSIFIED', max_length=20)),
            ],
            bases=('common.basemodel',),
        ),
    ]
