# Generated by Django 3.0.8 on 2020-07-23 13:33

import apps.v1.cervic_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervic_model', '0002_cervicclassification_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervicclassification',
            name='image',
            field=models.ImageField(upload_to=apps.v1.common.tools.get_default_file_name_format),
        ),
    ]
