# Generated by Django 3.0.8 on 2020-07-24 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200719_2031'),
        ('cervic_model', '0003_auto_20200723_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cervicclassification',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
