# Generated by Django 3.0.8 on 2020-07-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervic_model', '0004_auto_20200724_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='cervicclassification',
            name='new_result',
            field=models.IntegerField(choices=[(0, 'Unclassified'), (1, 'Negative'), (2, 'Positive'), (3, 'Unknown')], default=0),
        ),
        migrations.AddField(
            model_name='cervicclassification',
            name='new_status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Done')], default=0),
        ),
    ]
