# Generated by Django 3.0.8 on 2020-07-30 01:47

from django.db import migrations

forward_map_status = {
    'WAITING': 0,
    'DONE': 1,
}

forward_map_result = {
    'UNCLASSIFIED': 0,
    'NEGATIVE': 1,
    'POSITIVE': 2,
    'UNKNOWN': 3,
}

def update_status_and_result_value(apps, schema_editor):
    CervicClassification = apps.get_model('cervic_model', 'CervicClassification')
    
    for instance in CervicClassification.objects.all():
        instance.new_status = forward_map_status[instance.status]
        instance.new_result = forward_map_result[instance.result]
        instance.save()

def reverse_status_and_result_value(apps, schema_editor):
    CervicClassification = apps.get_model('cervic_model', 'CervicClassification')
    backward_map_status = {v: k for k, v in forward_map_status.items()}
    backward_map_result = {v: k for k, v in forward_map_result.items()}

    for instance in CervicClassification.objects.all():
        instance.status = backward_map_status[instance.new_status]
        instance.result = backward_map_result[instance.new_result]
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cervic_model', '0005_auto_20200730_0846'),
    ]

    operations = [
        migrations.RunPython(update_status_and_result_value, reverse_status_and_result_value)
    ]
