# Generated by Django 3.0.8 on 2020-07-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cervic_model', '0007_auto_20200730_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cervicclassification',
            old_name='new_result',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='cervicclassification',
            old_name='new_status',
            new_name='status',
        ),
    ]
