# Generated by Django 3.0.8 on 2020-08-13 17:30

import apps.v1.cervic_model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cervic_model', '0009_auto_20200813_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model', models.FileField(upload_to=apps.v1.cervic_model.models.get_default_file_name_format)),
                ('is_chosen', models.BooleanField(default=False)),
            ],
        ),
    ]
