# Generated by Django 3.0.8 on 2020-08-20 15:40

from django.db import migrations

map_to_new = {
    0: 99,
    1: 0,
    2: 1,
    3: 98,
}

map_to_old = {v: k for k, v in map_to_new.items()}

def map_result_code(map):
    def change_result_code(apps, schema_editor):
        CervicClassification = apps.get_model('cervic_model', 'CervicClassification')
        
        for instance in CervicClassification.objects.all():
            instance.result = map.get(instance.result, instance.result)
            instance.save()

    return change_result_code

class Migration(migrations.Migration):

    dependencies = [
        ('cervic_model', '0011_auto_20200820_2239'),
    ]

    operations = [
        migrations.RunPython(
            map_result_code(map_to_new),
            map_result_code(map_to_old),
        )
    ]
